services:
  database:
    image: docker.io/postgres:17
    container_name: ac-database
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - ac
    volumes:
      # mounts a named volume so that data survives restart
      - database:/var/lib/postgresql/data/
  redis-broker:
    image: docker.io/redis:8
    ports:
      - "${REDIS_BROKER_PORT}:6379"
  redis-database:
    image: docker.io/redis:8
    ports:
      - "${REDIS_DB_PORT}:6379"

networks:
  ac:

volumes:
  database:
